name: Actualizar data diariamente

on:
  schedule:
    - cron: '0 2 * * *'  # Todos los días a las 22:00 Chile (02:00 UTC)
  workflow_dispatch:      # También permite ejecutarlo manualmente

jobs:
  run-main:
    runs-on: ubuntu-latest

    env:
      APIFY_API_KEY: ${{ secrets.APIFY_API_KEY }}
      EMAIL_REMITENTE: ${{ secrets.EMAIL_REMITENTE }}
      EMAIL_CLAVE_APP: ${{ secrets.EMAIL_CLAVE_APP }}
      AZURE_BLOB_CONTAINER: ${{ secrets.AZURE_BLOB_CONTAINER }}
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar predicción principal
        run: |
          python src/main.py
