name: Actualizar data diariamente

on:
  schedule:
    - cron: '0 3 * * *'  # Todos los días a las 00:00 UTC
  workflow_dispatch:      # También puedes ejecutarlo manualmente

permissions:
  contents: write  # Permite hacer push al repo

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar scraping
        run: |
          python src/main.py

      - name: Configurar git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions[bot]"

      - name: Hacer commit si hay cambios
        run: |
          git add data/
          if git diff --cached --quiet; then
            echo "No hay cambios para commitear"
          else
            git commit -m "Actualizar data automáticamente"
            git push
          fi
