name: Actualizar data diariamente

on:
  schedule:
    - cron: '0 2 * * *'  # Todos los días a las 22:00 Chile (02:00 UTC)
  workflow_dispatch:      # Permite ejecutarlo manualmente

permissions:
  contents: write  # Requerido para hacer push al repo

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Descargar archivos de datos desde GitHub Releases
        run: |
          mkdir -p data
          wget -O data/raw_data.csv https://github.com/PolloDK/FK01-Encuestas/releases/download/v1.0-data/raw_data.csv
          wget -O data/preprocessed.csv https://github.com/PolloDK/FK01-Encuestas/releases/download/v1.0-data/preprocessed.csv
          wget -O data/sentiment_analysis.csv https://github.com/PolloDK/FK01-Encuestas/releases/download/v1.0-data/sentiment_analysis.csv
          wget -O data/embedding_data.csv https://github.com/PolloDK/FK01-Encuestas/releases/download/v1.0-data/embedding_data.csv
          wget -O data/processed_data.csv https://github.com/PolloDK/FK01-Encuestas/releases/download/v1.0-data/processed_data.csv
          wget -O data/features_dataset.csv https://github.com/PolloDK/FK01-Encuestas/releases/download/v1.0-data/features_dataset.csv

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar predicción
        run: |
          python src/main.py

      - name: Configurar git para commit automático
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions[bot]"

      - name: Hacer commit si hay cambios en data/
        run: |
          git add data/
          if git diff --cached --quiet; then
            echo "No hay cambios para commitear"
          else
            git commit -m "Actualizar data automáticamente"
            git push
          fi
